In [6]:
%matplotlib inline
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt

In [8]:
img = plt.imread('peppers.png')


[[[ 0.24313726  0.11372549  0.25098041]
  [ 0.24705882  0.12156863  0.25098041]
  [ 0.24705882  0.13333334  0.25098041]
  ..., 
  [ 0.25098041  0.11372549  0.22352941]
  [ 0.24705882  0.10980392  0.21568628]
  [ 0.25098041  0.10980392  0.21568628]]

 [[ 0.24705882  0.12156863  0.24313726]
  [ 0.23921569  0.12156863  0.25098041]
  [ 0.23137255  0.1254902   0.25098041]
  ..., 
  [ 0.23921569  0.10588235  0.21568628]
  [ 0.22745098  0.10588235  0.21176471]
  [ 0.21960784  0.10588235  0.21960784]]

 [[ 0.25490198  0.11372549  0.23529412]
  [ 0.24705882  0.11764706  0.24313726]
  [ 0.24705882  0.12156863  0.24705882]
  ..., 
  [ 0.25098041  0.10196079  0.21568628]
  [ 0.24313726  0.10588235  0.22352941]
  [ 0.22352941  0.10588235  0.22352941]]

 ..., 
 [[ 0.46666667  0.27843139  0.53333336]
  [ 0.4627451   0.27058825  0.53333336]
  [ 0.47058824  0.28627452  0.5529412 ]
  ..., 
  [ 0.17647059  0.08235294  0.17647059]
  [ 0.17647059  0.09411765  0.18039216]
  [ 0.15686275  0.09411765  0.16470